In [162]:
import pandas as pd

In [163]:
df = pd.read_csv("../Data/Tous votes Constituante - Sheet1.csv")
df.iloc[0]

FileNotFoundError: [Errno 2] No such file or directory: '../Tous votes Constituante - Sheet1.csv'

In [145]:
#filter the data set and only take 1ère lecture
filtered_df = df.drop(['startTime', 'endTime', 'filename','Unnamed: 0', 'affair','meaningYesText', 'meaningNoText', 'note', 'warning', 'linkVideo', 'attachment', 'DE_meaningYesText', 'DE_meaningNoText', 'DE_note', 'DE_affair', 'DE_section', 'DE_warning', 'DE_attachment'], axis=1)
filtered_df = filtered_df[filtered_df['section'].str.contains("1ère lecture")]
filtered_df.iloc[0]

label           Modif. Annexe 3 / Änderung Anhang 3 OUI / NON
affairVoteId                                   20211209163422
meaningYes                                           Accepter
meaningNo                                             Refuser
numYes                                                     93
numNo                                                       1
numAbst                                                     3
section                              1ère lecture - Structure
Name: 478, dtype: object

In [146]:
filtered_df['art_id'] = filtered_df['label'].apply(lambda x: x.rsplit(' ')[0])
filtered_df.head()

,label,affairVoteId,meaningYes,meaningNo,numYes,numNo,numAbst,section,art_id
478,Modif. Annexe 3 / Änderung Anhang 3 OUI / NON,20211209163422,Accepter,Refuser,93,1,3,1ère lecture - Structure,Modif.
479,Chap.9/Kap.9: A-R09.09 – AC OUI / NON,20211209163107,Accepter,Refuser,35,61,5,1ère lecture - Structure,Chap.9/Kap.9:
480,Chap.8/Kap.8: A-R08.08 – G. Schmid OUI / NON,20211209162931,Accepter,Refuser,20,78,5,1ère lecture - Structure,Chap.8/Kap.8:
481,Chap.8/Kap.8: A-R08.07 – AC OUI / NON,20211209162859,Accepter,Refuser,29,70,1,1ère lecture - Structure,Chap.8/Kap.8:
482,Chap.6/Kap.6: A-R06.04 – VLR OUI / NON,20211209161743,Accepter,Refuser,56,39,2,1ère lecture - Structure,Chap.6/Kap.6:

In [147]:
filtered_df.size

5040

In [148]:
#Check this part !!!!!!!!!
filtered_df = filtered_df[filtered_df['art_id'].str[0].str.isnumeric()]

In [149]:
filtered_df.head()

,label,affairVoteId,meaningYes,meaningNo,numYes,numNo,numAbst,section,art_id
488,"629a, vote 1 : Commission = A-629a.135 Carron ...",20211209145152,Accepter,Refuser,50,58,6,1ère lecture - Commission 6,"629a,"
489,"629, vote 4 : Resultat v.3 contre A-629.134 CV...",20211209145100,Accepter,Refuser,72,37,4,1ère lecture - Commission 6,"629,"
490,"629, vote 3 : Commission contre résultat V/A 2",20211209144933,Accepter,Refuser,47,65,3,1ère lecture - Commission 6,"629,"
491,"629, vote 2 : Résultat V/A 1 contre A-629.133 AC",20211209144856,Accepter,Refuser,60,51,4,1ère lecture - Commission 6,"629,"
492,"629, vote 1 : A-629.131 PDCVr contre A-629.132...",20211209144809,Accepter,Refuser,70,37,7,1ère lecture - Commission 6,"629,"

In [150]:
filtered_df.size

4752

In [151]:
filtered_df = filtered_df.drop_duplicates(subset=['art_id'], keep='first')

In [152]:
filtered_df.head()

,label,affairVoteId,meaningYes,meaningNo,numYes,numNo,numAbst,section,art_id
488,"629a, vote 1 : Commission = A-629a.135 Carron ...",20211209145152,Accepter,Refuser,50,58,6,1ère lecture - Commission 6,"629a,"
489,"629, vote 4 : Resultat v.3 contre A-629.134 CV...",20211209145100,Accepter,Refuser,72,37,4,1ère lecture - Commission 6,"629,"
493,"628, al. 2 / Abs. 2, vote 3 : Commission (y.c....",20211209123532,Accepter,Refuser,56,50,2,1ère lecture - Commission 6,"628,"
497,"627, vote 2 : Commission (y.c. V/A 1) contre A...",20211209115926,Accepter,Refuser,74,30,8,1ère lecture - Commission 6,"627,"
499,"617, vote 6 : Commission (y.c. V/A 1-5) contre...",20211209114349,Accepter,Refuser,94,12,3,1ère lecture - Commission 6,"617,"

In [153]:
ids_vote = filtered_df['affairVoteId'].to_csv('votation_ids.csv')

In [154]:
def political_orientation(x):
    if x == 'PDC' or x == 'SVPO' or x == 'CSPO' or x =='CVPO':
        return 'CD'
    elif x == 'VLR' or x == 'UDC':
        return 'D'
    else:
        return 'G'
def vote_transformation(x):
    if x == 'Oui/Ja':
        return 'oui'
    elif x == 'Non/Nein':
        return 'non'
    elif x == 'Abst./Enth.':
        return 'abst'
    else: 
        return 'aucun'

In [155]:
df1 = pd.DataFrame(['D', 'CD', 'G'])
df2 = pd.DataFrame(['oui', 'non', 'aucun', 'abst'])
orientation_df = df1.merge(df2, how='cross')
orientation_df.columns=['group', 'vote']
orientation_df.head()

  group   vote
0     D    oui
1     D    non
2     D  aucun
3     D   abst
4    CD    oui

In [156]:
ids_vote = filtered_df['affairVoteId']
full_votes = pd.DataFrame()
for ids in ids_vote:
    temp_df = pd.read_csv("../Data/{}.csv".format(ids))
    #for group, vote in orientation_df.enumerate():
        
    full_votes = pd.concat([full_votes, temp_df])
temp_df = full_votes
temp_df['group'] = temp_df['group'].apply(lambda x: political_orientation(x))
temp_df['vote'] = temp_df['vote'].apply(lambda x: vote_transformation(x))
print(temp_df)

                    name group   vote Genre  Âge        District  \
0       Matteo ABÄCHERLI    CD   abst     H   33            Visp
1        Claudia ALPIGER     G    oui     F   32            Brig
2         Romano AMACKER    CD    non     H   24  Westlich Raron
3           Peter BÄHLER    CD    non     H   68            Goms
4       Gabrielle BARRAS     D    non     F   58            Sion
..                   ...   ...    ...   ...  ...             ...
125  Christelle HERITIER     D  aucun     F   36            Sion
126        Claude NANÇOZ     D  aucun     H   69         Conthey
127   Bernard OBERHOLZER     G  aucun     H   76         Monthey
128        Damien RABOUD     D  aucun     H   35         Monthey
129        Fabien THETAZ     G  aucun     H   35         Monthey

       affairVoteId
0    20211209145152
1    20211209145152
2    20211209145152
3    20211209145152
4    20211209145152
..              ...
125  20211005101833
126  20211005101833
127  20211005101833
128  20211005101833
129  20211005101833

[23140 rows x 7 columns]

In [157]:
ori_df = pd.DataFrame()
columns = []
for group, vote in zip(orientation_df.group, orientation_df.vote):
    ori_df[("{}, {}".format(group, vote))]=""
ori_df['affairVoteId'] = ""
ori_df.head()

Empty DataFrame
Columns: [D, oui, D, non, D, aucun, D, abst, CD, oui, CD, non, CD, aucun, CD, abst, G, oui, G, non, G, aucun, G, abst, affairVoteId]
Index: []

In [158]:
def add_elems(x):
    if x[1] == 'D':
        if x[2] == 'oui':
            return 'D, oui'
        elif x[2] == 'non':
            return 'D, non'
        elif x[2] == 'aucun':
            return 'D, aucun'
        else :
            return 'D, abst'
    elif x[1] == 'CD':
        if x[2] == 'oui':
            return 'CD, oui'
        elif x[2] == 'non':
            return 'CD, non'
        elif x[2] == 'aucun':
            return 'CD, aucun'
        else :
            return 'CD, abst'
    else: 
        if x[2] == 'oui':
            return 'G, oui'
        elif x[2] == 'non':
            return 'G, non'
        elif x[2] == 'aucun':
            return 'G, aucun'
        else :
            return 'G, abst'

In [159]:
counts_df = temp_df.groupby(['affairVoteId','group', 'vote']).size()
index = -1
art_id = 0
for ids, val in zip(counts_df.keys(), counts_df):
    temp_art_id = ids[0]
    if(art_id != temp_art_id):
        #print(ids)
        index += 1
        ori_df.at[index,'affairVoteId'] = ids[0]
        art_id = temp_art_id

    if ids[1] =='CD':
        if ids[2] == 'oui':
            ori_df.at[index,"{}".format(add_elems(ids))] = 0.5*val/54
        elif ids[2] == 'non':
            #print(-(0.3*val/54))
            ori_df.at[index,"{}".format(add_elems(ids))] = -(0.5*val/54)
        else:
            ori_df.at[index,"{}".format(add_elems(ids))] = 0
    elif ids[1] =='G':
        if ids[2] == 'oui':
            ori_df.loc[index,"{}".format(add_elems(ids))] = -(val/41)
        elif ids[2] == 'non':
            ori_df.loc[index,"{}".format(add_elems(ids))] = val/41
    else :
        if ids[2] =='oui':
            ori_df.at[index,"{}".format(add_elems(ids))] = val*0.5/35
        elif ids[2] == 'non':
            ori_df.at[index,"{}".format(add_elems(ids))] = -(0.5*val/35)
ori_df = ori_df.fillna(0)
ori_df.head(15)

,"D, oui","D, non","D, aucun","D, abst","CD, oui","CD, non","CD, aucun","CD, abst","G, oui","G, non","G, aucun","G, abst",affairVoteId
0,0.257143,-0.142857,0,0,0.101852,-0.379630,0,0,-0.658537,0.268293,0,0,20211005101833
1,0.371429,-0.014286,0,0,0.259259,-0.166667,0,0,-0.902439,0.024390,0,0,20211005103758
2,0.271429,-0.157143,0,0,0.472222,-0.009259,0,0,-0.902439,0.024390,0,0,20211005104632
3,0.171429,-0.242857,0,0,0.120370,-0.342593,0,0,-0.707317,0.121951,0,0,20211005105440
4,0.271429,-0.171429,0,0,0.444444,-0.046296,0,0,-0.926829,0.000000,0,0,20211005110548
5,0.214286,-0.214286,0,0,0.000000,-0.490741,0,0,-0.341463,0.585366,0,0,20211005113841
6,0.028571,-0.400000,0,0,0.324074,-0.157407,0,0,-0.073171,0.804878,0,0,20211005115057
7,0.285714,-0.157143,0,0,0.425926,-0.055556,0,0,-0.902439,0.000000,0,0,20211005121022
8,0.257143,-0.185714,0,0,0.370370,-0.120370,0,0,-0.804878,0.073171,0,0,20211005141356
9,0.185714,-0.257143,0,0,0.129630,-0.361111,0,0,-0.073171,0.829268,0,0,20211005144844
10,0.342857,-0.085714,0,0,0.398148,-0.037037,0,0,-0.121951,0.731707,0,0,20211005152940
11,0.185714,-0.228571,0,0,0.194444,-0.259259,0,0,-0.536585,0.390244,0,0,20211005155125
12,0.214286,-0.242857,0,0,0.416667,-0.055556,0,0,-0.146341,0.780488,0,0,20211005161201
13,0.185714,-0.242857,0,0,0.388889,-0.083333,0,0,-0.341463,0.414634,0,0,20211005164852
14,0.185714,-0.228571,0,0,0.453704,-0.009259,0,0,-0.097561,0.780488,0,0,20211005171134

In [160]:
#We divide by two to normalize since we are taking into account the no votes
final_ori_df = pd.DataFrame(columns=['affairVoteId', 'orientation'])
final_ori_df['affairVoteId'] = ori_df['affairVoteId']
final_ori_df['orientation'] = (ori_df['D, oui'] + ori_df['D, non'] + ori_df['CD, oui'] + ori_df['CD, non'] + ori_df['G, oui'] + ori_df['G, non'])/2
final_ori_df.head(15)

      affairVoteId  orientation
0   20211005101833    -0.276868
1   20211005103758    -0.214157
2   20211005104632    -0.150400
3   20211005105440    -0.439508
4   20211005110548    -0.214341
5   20211005113841    -0.123419
6   20211005115057     0.263473
7   20211005121022    -0.201749
8   20211005141356    -0.205139
9   20211005144844     0.226594
10  20211005152940     0.614005
11  20211005155125    -0.127007
12  20211005161201     0.483343
13  20211005164852     0.160792
14  20211005171134     0.542257

In [161]:
final_df = pd.merge(pd.merge(filtered_df, final_ori_df, on='affairVoteId'), full_votes, on='affairVoteId')
final_df.head()

,label,affairVoteId,meaningYes,meaningNo,numYes,numNo,numAbst,section,art_id,orientation,name,group,vote,Genre,Âge,District
0,"629a, vote 1 : Commission = A-629a.135 Carron ...",20211209145152,Accepter,Refuser,50,58,6,1ère lecture - Commission 6,"629a,",-0.673655,Matteo ABÄCHERLI,CD,abst,H,33,Visp
1,"629a, vote 1 : Commission = A-629a.135 Carron ...",20211209145152,Accepter,Refuser,50,58,6,1ère lecture - Commission 6,"629a,",-0.673655,Claudia ALPIGER,G,oui,F,32,Brig
2,"629a, vote 1 : Commission = A-629a.135 Carron ...",20211209145152,Accepter,Refuser,50,58,6,1ère lecture - Commission 6,"629a,",-0.673655,Romano AMACKER,CD,non,H,24,Westlich Raron
3,"629a, vote 1 : Commission = A-629a.135 Carron ...",20211209145152,Accepter,Refuser,50,58,6,1ère lecture - Commission 6,"629a,",-0.673655,Peter BÄHLER,CD,non,H,68,Goms
4,"629a, vote 1 : Commission = A-629a.135 Carron ...",20211209145152,Accepter,Refuser,50,58,6,1ère lecture - Commission 6,"629a,",-0.673655,Gabrielle BARRAS,D,non,F,58,Sion